
# Hellinger Distance Optimization
name: hdo

# the temperature parameter for KL optimization
beta: 0.1

# moving average rate for tracking rejected ratios
#moving_avg_rate: 0.1

trainer: HDOTrainer

dataloader: UnpairedPreferenceDataLoader

use_reference_model: true
